In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df_customers = pd.read_csv("Raw_Data/customers.csv")
df_customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        5000 non-null   str
 1   full_name          4894 non-null   str
 2   age                4814 non-null   float64
 3   gender             4888 non-null   str
 4   email              4889 non-null   str
 5   phone              4814 non-null   str
 6   street_address     4823 non-null   str
 7   city               4903 non-null   str
 8   state              4907 non-null   str
 9   zip_code           4904 non-null   float64
 10  registration_date  5000 non-null   str
 11  preferred_channel  4886 non-null   str
dtypes: float64(2), str(10)
memory usage: 468.9 KB

<>:1: SyntaxWarning: "\E" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\E"? A raw string is also an option.
<>:1: SyntaxWarning: "\E" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\E"? A raw string is also an option.
C:\Users\Pitiki_\AppData\Local\Temp\ipykernel_5376\3204070042.py:1: SyntaxWarning: "\E" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\E"? A raw string is also an option.
  df_customers = pd.read_csv("A:\Escritorio\Proyectos DATA\CRM\end-to-end-saas-pipeline\Raw_Data\customers.csv")

In [15]:
df_transactions = pd.read_csv("Raw_Data/transactions.csv")
df_transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 32295 entries, 0 to 32294
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    32295 non-null  str
 1   customer_id       32295 non-null  str
 2   product_name      31617 non-null  str
 3   product_category  31609 non-null  str
 4   quantity          31651 non-null  float64
 5   price             31673 non-null  float64
 6   transaction_date  32295 non-null  str
 7   store_location    31651 non-null  str
 8   payment_method    31635 non-null  str
 9   discount_applied  31684 non-null  float64
dtypes: float64(3), str(7)
memory usage: 2.5 MB

In [17]:
df_transactions.isnull().sum().loc[lambda x: x > 0]

product_name        678
product_category    686
quantity            644
price               622
store_location      644
payment_method      660
discount_applied    611
dtype: int64

In [26]:
nulos_quantity = df_transactions[df_transactions["quantity"].isnull()]
nulos_quantity

,transaction_id,customer_id,product_name,product_category,quantity,price,transaction_date,store_location,payment_method,discount_applied
6,2936863b-85c8-410d-8ff7-ae59fa28ce8b,1b194bc2-2033-4e79-912c-91e3fd9d02cc,Range Hood,Kitchen Appliances,NaN,989.55,2022-12-24,"Denver, CO",Gift Card,0.0
81,dee43294-9457-4d76-b6ba-a2a0c169268d,b710feb2-0df6-4c04-b3ff-1f89fe14a1c1,OnePlus 10,Smartphones,NaN,1216.36,2025-01-17,Online,Apple Pay,25.0
123,8702ef73-896b-4355-8f3e-0c1adb8bd7df,dc63a831-e571-4032-a2e9-1e1abf21834b,Microwave Oven,Kitchen Appliances,NaN,508.96,2022-02-10,Online,Credit Card,15.0
166,2dae2dda-4ed2-4c94-9c76-66c46cf0247e,cb035960-9c0a-4e49-83b3-48d1fa55b763,Google Pixel 6,Smartphones,NaN,1052.66,2023-08-19,Online,Credit Card,15.0
198,33b08928-e385-4aaf-b6be-994f7ebfada1,3e4fc6c7-0024-4219-99de-65f9649c8b90,Xiaomi Mi 12,Smartphones,NaN,380.41,2022-07-19,Online,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...
32197,d33a3be5-e920-4d71-a537-418754beeccf,b876c2a8-6999-4262-b298-57f95070c3f8,Dishwasher,Kitchen Appliances,NaN,767.19,2022-11-02,Online,Credit Card,0.0
32217,3ba7d77d-2900-4ef6-89aa-b3f0c1e87cf6,d12653ce-6f6d-44a6-97fb-b2e31c844b26,Wall Art,Home Decor,NaN,49.73,2020-11-07,Online,PayPal,0.0
32229,0d0af33f-8056-460b-ae82-1402357d848b,0874d5de-720b-49bf-904e-1b1800e3e283,Dining Table,Furniture,NaN,1715.32,2021-05-13,"Chicago, IL",Gift Card,0.0
32248,8fe725d9-ff63-4a48-878f-0ec9fae1d02f,317ae7ef-540b-4bd3-bea2-c43479460633,Refrigerator,Kitchen Appliances,NaN,304.84,2023-03-31,"Atlanta, GA",Credit Card,0.0
32259,26f7f63c-73c5-42e5-b05c-886f86c97954,5e4aaf11-21fd-4847-94eb-00d778eb4cf5,Office Desk,Furniture,NaN,447.86,2024-10-18,"Boston, MA",Credit Card,10.0

In [25]:
nulos_price = df_transactions[df_transactions["price"].isnull()]
nulos_price

,transaction_id,customer_id,product_name,product_category,quantity,price,transaction_date,store_location,payment_method,discount_applied
25,bdacbf5e-31fa-4129-b616-e88a763551d6,8fdebd08-fc33-448b-9e36-9480c10d3d4a,Xbox Series X,Gaming Consoles,1.0,NaN,2021-08-06,Online,PayPal,0.0
44,bcce175c-001e-4e07-b5c1-8b48c7adf848,0457e8c4-10bc-4d63-a9e8-4068fe3d50b7,NaN,Smart Home Devices,2.0,NaN,2023-05-28,Online,Credit Card,15.0
59,047bfb7f-756e-4065-8a39-0bfee6759bc6,e22a7771-562b-4d6a-a255-cd46330ac39d,Microwave Oven,Kitchen Appliances,1.0,NaN,2022-08-18,Online,Apple Pay,0.0
152,3c5e7795-3ae7-4aa1-9cd3-0e21381535b8,39d8d6cd-7cc8-441f-b3c3-e6092fe25682,Ring Doorbell,Smart Home Devices,1.0,NaN,2023-09-11,"New York, NY",Apple Pay,0.0
156,b9f2aa2d-4555-4cd2-be84-34fbc550a558,d42b09fd-089d-41c5-82ce-4788f75217a6,Range Hood,Kitchen Appliances,1.0,NaN,2022-05-30,Online,Credit Card,5.0
...,...,...,...,...,...,...,...,...,...,...
32237,9f451eba-9154-4619-a4e9-ea09fbf235a4,da5f8816-8959-455b-8787-b370200d593a,JBL Bluetooth Speaker,Audio Equipment,1.0,NaN,2023-07-08,Online,Credit Card,0.0
32240,4e17dbcb-303b-4825-8ba1-c7da5cd3a830,ee0e9368-11e4-467a-9f68-cce203fe24ea,Knife Set,Cookware,2.0,NaN,2024-12-14,Online,Google Pay,NaN
32260,0631f0d9-e0d9-4e83-b452-3b2840f1d9bf,97af8e28-1922-45a8-b0f8-1e1b7632fe13,Google Pixel 6,Smartphones,2.0,NaN,2021-01-19,Online,Credit Card,0.0
32281,63f84928-41a4-4145-ace8-52b19e042aad,f37c8e8a-dcf8-48d2-b1fa-2add6bb73f7e,HP Spectre,Laptops,1.0,NaN,2021-12-22,"Los Angeles, CA",Credit Card,0.0
32291,47eaf0c3-0ec2-4b1d-8744-f293dfdc1c00,48405c0e-84f6-41d1-bde3-0ad2511dd911,Sony Soundbar,Audio Equipment,1.0,NaN,2023-09-10,Online,Credit Card,0.0

In [24]:
nulos_product_name = df_transactions[df_transactions["product_name"].isnull()]

nulos_product_name

,transaction_id,customer_id,product_name,product_category,quantity,price,transaction_date,store_location,payment_method,discount_applied
9,0b0e3abe-fbe2-478b-b36f-6a5f95f27a9f,2bfcd9ca-a7e1-48ab-8a46-9b2804333a53,NaN,Kitchen Appliances,1.0,1033.261129,2024-01-08,Online,Debit Card,10.0
14,28ebb323-3096-48a7-9624-ab5454fafed4,90655f4c-d1fa-48fa-8eec-cfdadc9a61f2,NaN,Home Decor,2.0,312.730000,2022-11-17,Online,Credit Card,15.0
44,bcce175c-001e-4e07-b5c1-8b48c7adf848,0457e8c4-10bc-4d63-a9e8-4068fe3d50b7,NaN,Smart Home Devices,2.0,NaN,2023-05-28,Online,Credit Card,15.0
63,f9a28210-a8a1-4f70-bde4-f524be3f09d6,f5e14882-6051-40b2-8a94-740ab2d08da8,NaN,Home Decor,1.0,145.270000,2022-11-06,Online,Debit Card,0.0
68,e39e76cf-147f-43c8-a4de-683ddd7aabb9,245cff68-0bc2-4ccf-85b6-bb3bce182d0c,NaN,Audio Equipment,1.0,203.240000,2024-07-27,Online,Google Pay,0.0
...,...,...,...,...,...,...,...,...,...,...
31940,a4cb66eb-a267-43ce-9480-62bf0464af74,27810953-cb07-4811-92ff-760a913753c1,NaN,Smart Home Devices,1.0,259.810000,2024-07-30,"Chicago, IL",Apple Pay,0.0
31960,048122bc-f457-420e-9143-db35c1730c22,4accc613-fb41-4dbd-ae53-7c4e93c7a2cc,NaN,Gaming Consoles,2.0,456.820000,2024-12-15,"Houston, TX",Credit Card,0.0
32153,db1f0b10-fff4-4115-bf34-e0d2402c32d9,91d90200-5474-41ac-bc95-d8a3ed24e3c2,NaN,Audio Equipment,1.0,108.250000,2024-11-18,"New York, NY",Debit Card,10.0
32160,372a4dfe-dfb6-4844-8bc0-cbab4a8ff19e,1066b45b-d15e-4bfc-b0bb-8b8ce474d366,NaN,Furniture,1.0,974.520000,2024-05-10,Online,Gift Card,0.0
32261,7e377376-f40e-4283-96bf-1a2720b7a37f,9a86fdf2-18b9-4407-bc89-164cb499aae7,NaN,Laptops,1.0,2083.250000,2023-04-17,Online,PayPal,0.0